test-5 main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -15,21 +15,22 @@ jobs:
       - name: Check out the repository
         uses: actions/checkout@v4
 
-      - name: Check if README.md and .version files exist
+      - name: Check if README.md exists
         run: |
           if [ ! -f README.md ]; then
             echo "README.md is missing" && exit 1
           fi
-          if [ ! -d .version/ ]; then
-            echo ".version file is missing" && exit 1
+
+          if [ ! -d ".version" ]; then
+            echo ".version is missing" && exit 1
           fi
 
-      - name: Syntax check for install.sh and scripts in src/ (exclude SC1090)
+      - name: Syntax check for install.sh and scripts in src/.install/ (exclude SC1090 and SC2086)
         run: |
           if [ -f install.sh ]; then
-            shellcheck -e SC1090 install.sh || { echo "Syntax check failed for install.sh"; exit 1; }
+            shellcheck -e SC1090,SC2086 install.sh || { echo "Syntax check failed for install.sh"; exit 1; }
           fi
-          find src -name "*.sh" -print0 | xargs -0 -n1 shellcheck -e SC1090 || exit 1
+          find src/.install -name "*.sh" -print0 | xargs -0 -n1 shellcheck -e SC1090,SC2086 || exit 1
 
       - name: Run install.sh (dry run mode)
         run: |
