test-7 main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,5 +1,3 @@
-name: CI
-
 on:
   push:
     branches: [ "master" ]
@@ -18,7 +16,7 @@ jobs:
       - name: Check if README.md exists
         run: |
           if [ ! -f README.md ]; then
-            exit 1
+            echo "README.md is missing" && exit 1
           fi
 
           if [ ! -d ".version" ]; then
@@ -31,10 +29,6 @@ jobs:
             shellcheck -e SC1090,SC2086,SC2024,SC2164 install.sh || { echo "Syntax check failed for install.sh"; exit 1; }
           fi
           find src/.install -name "*.sh" -print0 | xargs -0 -n1 shellcheck -e SC1090,SC2086,SC2024,SC2164 || exit 1
-
-      - name: Run install.sh (dry run mode)
-        run: |
-          bash install.sh --dry-run || echo "Dry run of install.sh failed" && exit 1
 
       - name: Validate configuration files in dotfiles directory
         run: |
@@ -54,3 +48,4 @@ jobs:
                 ;;
             esac
           done
+
